spring:
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true

#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa

  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
#            client-id: ${google.client-id}
#            client-secret: ${google.client-secret}
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_PW}
            scope:
              - email
              - profile

jwt:
  issuer: ajufresh@gmail.com
#  secret_key: study-springboot
  secret_key: ${JWT_SECRET_KEY}